baseURL: https://ljungbladsolutions.github.io/
languageCode: en-us
title: Ljungblad Solutions
theme: PaperMod5
defaultTheme: light
googleAnalytics: UA-214855469-1

menu:
  main:
    - identifier: about
      name: About
      title: About me
      url: /about/
      weight: -100
    - identifier: archives
      name: Archive
      title: blog section
      url: /archives/
      weight: -300
    - identifier: Categories
      name: Categories
      title: Categories
      url: /categories/
      weight: -200

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "A blog about Software development, architecture and other things."
  author: Christopher Ljungblad
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true #Show table of content
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: true
    title: Christopher Ljungblad
   # imageUrl: "/images/pencil-square.svg"
    imageUrl: "/images/favicon_io/android-chrome-192x192.png"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archive
        url: archives
      - name: Categories
        url: categories

  homeInfoParams:
    Title: "Christopher Ljungblad"
    Content:
  socialIcons:
    - name: github
      url: "https://github.com/ljungbladsolutions/"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/ljungblad/"
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/favicon_io/favicon.ico"
    favicon16x16: "/images/favicon_io/favicon-16x16.png"
    favicon32x32: "/images/favicon_io/favicon-16x16.png"
    apple_touch_icon: "/images/favicon_io/apple-touch-icon-png"

taxonomies:
  tag: "tags"
  category: "categories"





